// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Wasla_App.Data;

#nullable disable

namespace Wasla_App.Migrations
{
    [DbContext(typeof(ContexteBaseDonnees))]
    partial class ContexteBaseDonneesModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Wasla_App.Models.Billet", b =>
                {
                    b.Property<int>("NewBilletID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("NewBilletID"));

                    b.Property<int>("CompagnieID")
                        .HasColumnType("int");

                    b.Property<DateTime>("DateVoyage")
                        .HasColumnType("datetime2");

                    b.Property<int>("LigneID")
                        .HasColumnType("int");

                    b.Property<string>("NomUtilisateur")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("NumeroSiege")
                        .HasColumnType("int");

                    b.Property<string>("StatutPaiement")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("NewBilletID");

                    b.HasIndex("CompagnieID");

                    b.HasIndex("LigneID");

                    b.ToTable("Billets");
                });

            modelBuilder.Entity("Wasla_App.Models.Compagnie", b =>
                {
                    b.Property<int>("CompagnieID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CompagnieID"));

                    b.Property<string>("NomCompagnie")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CompagnieID");

                    b.ToTable("Compagnies");
                });

            modelBuilder.Entity("Wasla_App.Models.LigneBus", b =>
                {
                    b.Property<int>("LigneID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LigneID"));

                    b.Property<int>("CompagnieID")
                        .HasColumnType("int");

                    b.Property<string>("NomLigne")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("VilleArriveeID")
                        .HasColumnType("int");

                    b.Property<int>("VilleDepartID")
                        .HasColumnType("int");

                    b.HasKey("LigneID");

                    b.HasIndex("CompagnieID");

                    b.HasIndex("VilleArriveeID");

                    b.HasIndex("VilleDepartID");

                    b.ToTable("LignesBus");
                });

            modelBuilder.Entity("Wasla_App.Models.Utilisateur", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MotDePasse")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Utilisateurs");
                });

            modelBuilder.Entity("Wasla_App.Models.Ville", b =>
                {
                    b.Property<int>("VilleID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("VilleID"));

                    b.Property<string>("NomVille")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("VilleID");

                    b.ToTable("Villes");
                });

            modelBuilder.Entity("Wasla_App.Models.Billet", b =>
                {
                    b.HasOne("Wasla_App.Models.Compagnie", "Compagnie")
                        .WithMany()
                        .HasForeignKey("CompagnieID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Wasla_App.Models.LigneBus", "LigneBus")
                        .WithMany()
                        .HasForeignKey("LigneID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Compagnie");

                    b.Navigation("LigneBus");
                });

            modelBuilder.Entity("Wasla_App.Models.LigneBus", b =>
                {
                    b.HasOne("Wasla_App.Models.Compagnie", "Compagnie")
                        .WithMany()
                        .HasForeignKey("CompagnieID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Wasla_App.Models.Ville", "VilleArrivee")
                        .WithMany()
                        .HasForeignKey("VilleArriveeID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Wasla_App.Models.Ville", "VilleDepart")
                        .WithMany()
                        .HasForeignKey("VilleDepartID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Compagnie");

                    b.Navigation("VilleArrivee");

                    b.Navigation("VilleDepart");
                });
#pragma warning restore 612, 618
        }
    }
}
